#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
#
# 15.04.2010  Wait for dropbear before phoning controller
#
START=99

check_for_dropbear()    {
        #db_listen=`netstat -t -l -n  -p 2>&1 | grep dropbear | wc -l`
        db_listen=`netstat -t -l -n  2>&1 | grep ":22 " | wc -l`
        return $db_listen
}





start() {

        echo "phone_home: Waiting for Dropbear startup"
        for try in 1 2 3 4 5 6 7 8 9
        do
          check_for_dropbear
          if [  $? -eq 0 ]
          then
              echo "phone_home: Dropbear not running yet. Waiting for some more"
              sleep 5
            else
                echo "phone_home: Dropbear is up!"
                break
            fi
        done

        echo "phone_home: Phoning home"

        CONTROLLER=`uci get network.lan.gateway`
        MY_IP=`uci get network.lan.ipaddr`

        echo $MY_IP | nc $CONTROLLER 9483
}

stop() {
        echo "Going down"
}
