#!/bin/bash
#
# This is executed in a chroot inside the mounted image
#
# Image wil be mounted to <setup>/mnt
#
# This sets IP address and hostname
#
# This file is for the node setup, i.e. it will be excuted once for EVERY
# image
#
# DO NOT edit this file. Do have additonal setup code put it in  a
# modify_image_node.sh image in your <setup> directory
#
# Parameter <image> <setup> <ip> <nodename>  <gateway> <dns> <ssh public key>
#
# (c) 2010 IBR


IMAGE=$1
SETUP=$2
IP=$3
NODENAME=$4
GATEWAY=$5
DNS=$6
SSHPUBKEY=$7

echo "------- Node setup ---------------------------------------------------"

echo "Preparing image in $IMAGE with"
echo "Node address  : $IP"
echo "Node name     : $NODENAME"
echo "Gateway       : $GATEWAY"
echo "DNS server    : $DNS"



if [ ! -e "$IMAGE" ]
then
   echo "$0: Can not find image  $IMAGE"
   exit -1
fi


bash $SETUP/magicmount.sh "$IMAGE" "$SETUP/mnt/"

# add ssh key to image
echo "copy SSH key $SSHPUBKEY"
mkdir -p $SETUP/mnt/etc/dropbear
cat $SETUP/$SSHPUBKEY >> $SETUP/mnt/etc/dropbear/authorized_keys

# switch to chroot
chroot "$SETUP/mnt/" /bin/sh <<EOF

# set permissions of authorized_keys file
chmod 0600 /etc/dropbear/authorized_keys

# set the nameserver
echo "nameserver $DNS" > /etc/resolv.conf

# configure network
uci delete network.lan.ipaddr
uci delete network.lan.netmask
uci delete network.lan.type
uci set network.lan.proto=static
uci set network.lan.ipaddr=$IP
uci set network.lan.dns=$DNS
uci set network.lan.netmask=255.255.255.0
uci set network.lan.gateway=$GATEWAY
uci set system.@system[0].hostname=$NODENAME
uci commit network
uci commit system.@system[0].hostname



# close chroot
EOF


#custom setup preparation
echo ">>>>> Custom image setup"
chroot "$SETUP/mnt/" /bin/sh /modify_image_node.sh "$IP" "$NODENAME"
echo ">>>>> Custom image setup done."


umount "$SETUP/mnt/"

echo "------- Node setup done ------------------------------------------------"