#!/bin/bash
#
# This is executed in a chroot inside the mounted image
#
# Image wil be mounted to <setup>/mnt
#
# All files from <setup>/overlay will be copied to the chroot
# All packages from <setup>packages will be installed in chroot
#
# This file is for the base setup, i.e. it will be excuted only ONCE and all
# changes done  by this file are copied to all nodes
#
# DO NOT edit this file. Do have additonal setup code put it in  a
# modify_image_base.sh image in your <setup> directory
#
# Parameter <image file> <setup>
#
# 2010 IBR


IMAGE_FILE=$1
SETUP=$2

echo "------- Image setup ---------------------------------------------------"

echo "Preparing image $IMAGE_FILE with"
echo "Configuration : $SETUP"

if [ ! -e "$IMAGE_FILE" ]
then
   echo "$0: Can't see image file $1"
   exit -1
fi

if [ ! -d "$SETUP" ]
then
   echo "$0: Can not find setup directory  $2"
   exit -1
fi


if [ ! -e "$SETUP/mnt" ]
then
    mkdir "$SETUP/mnt"
fi


# mount the image
bash ../data/magicmount.sh "$IMAGE_FILE" "$SETUP/mnt/"


#We need DNS capability in chroot
cp /etc/resolv.conf $SETUP/mnt/tmp/resolv.conf

# install packages
echo "Installing packages"
PACKAGES=`cat $SETUP/packages.install | grep -v "^#"`

chroot $SETUP/mnt /bin/sh -c "mkdir /var/lock"
chroot $SETUP/mnt opkg update

for pkg in $PACKAGES
do
    echo "Install $pkg"
    cp "$SETUP/packages/$pkg" "$SETUP/mnt/"
    chroot $SETUP/mnt /bin/sh -c "opkg install /*.ipk && rm /*.ipk"
done

#copy
echo "Copying overlay"
cp -r -f $SETUP/overlay/*  "$SETUP/mnt/"
cp -v "$SETUP/modify_image_base.sh" "$SETUP/mnt/"
cp -v "$SETUP/modify_image_node.sh" "$SETUP/mnt/"
cp -v "../data/phone_home" "$SETUP/mnt/etc/init.d/"

#custom setup preparation
echo ">>>>> Custom image setup"
chroot $SETUP/mnt /bin/sh /modify_image_base.sh 
echo ">>>>> Custom image setup done."

# switch to chroot
chroot "$SETUP/mnt" /bin/sh <<EOF

# change permissions
chmod 0755 /etc/init.d/phone_home

# enable node initrc
/etc/init.d/phone_home enable

# close chroot
EOF

# unmount the image
umount  "$SETUP/mnt/"

echo "------- Image setup done ------------------------------------------------"
